name: API Automation CI/CD Pipeline
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      # 🎯 تشغيل التيستات مع إجبار جيت هاب على تحديث وتنزيل الـ Dependencies النضيفة
      - name: Run Rest Assured Tests
        run: mvn clean test -U
        continue-on-error: true

      # جلب التاريخ القديم للمسار الموحد
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history

      # توليد التقرير
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: "**/allure-results"
          allure_history: allure-history
          keep_reports: 20

      # رفع التقرير النهائي
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
